// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: calls.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Calls_StartOutgoingCall_FullMethodName   = "/calls.v1.Calls/StartOutgoingCall"
	Calls_SubscribeCallEvents_FullMethodName = "/calls.v1.Calls/SubscribeCallEvents"
	Calls_HangupCall_FullMethodName          = "/calls.v1.Calls/HangupCall"
)

// CallsClient is the client API for Calls service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CallsClient interface {
	StartOutgoingCall(ctx context.Context, in *StartOutgoingCallRequest, opts ...grpc.CallOption) (*StartOutgoingCallResponse, error)
	SubscribeCallEvents(ctx context.Context, in *SubscribeCallEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CallEvent], error)
	HangupCall(ctx context.Context, in *HangupCallRequest, opts ...grpc.CallOption) (*HangupCallResponse, error)
}

type callsClient struct {
	cc grpc.ClientConnInterface
}

func NewCallsClient(cc grpc.ClientConnInterface) CallsClient {
	return &callsClient{cc}
}

func (c *callsClient) StartOutgoingCall(ctx context.Context, in *StartOutgoingCallRequest, opts ...grpc.CallOption) (*StartOutgoingCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartOutgoingCallResponse)
	err := c.cc.Invoke(ctx, Calls_StartOutgoingCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callsClient) SubscribeCallEvents(ctx context.Context, in *SubscribeCallEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CallEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Calls_ServiceDesc.Streams[0], Calls_SubscribeCallEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeCallEventsRequest, CallEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Calls_SubscribeCallEventsClient = grpc.ServerStreamingClient[CallEvent]

func (c *callsClient) HangupCall(ctx context.Context, in *HangupCallRequest, opts ...grpc.CallOption) (*HangupCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HangupCallResponse)
	err := c.cc.Invoke(ctx, Calls_HangupCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CallsServer is the server API for Calls service.
// All implementations must embed UnimplementedCallsServer
// for forward compatibility.
type CallsServer interface {
	StartOutgoingCall(context.Context, *StartOutgoingCallRequest) (*StartOutgoingCallResponse, error)
	SubscribeCallEvents(*SubscribeCallEventsRequest, grpc.ServerStreamingServer[CallEvent]) error
	HangupCall(context.Context, *HangupCallRequest) (*HangupCallResponse, error)
	mustEmbedUnimplementedCallsServer()
}

// UnimplementedCallsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCallsServer struct{}

func (UnimplementedCallsServer) StartOutgoingCall(context.Context, *StartOutgoingCallRequest) (*StartOutgoingCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartOutgoingCall not implemented")
}
func (UnimplementedCallsServer) SubscribeCallEvents(*SubscribeCallEventsRequest, grpc.ServerStreamingServer[CallEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeCallEvents not implemented")
}
func (UnimplementedCallsServer) HangupCall(context.Context, *HangupCallRequest) (*HangupCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HangupCall not implemented")
}
func (UnimplementedCallsServer) mustEmbedUnimplementedCallsServer() {}
func (UnimplementedCallsServer) testEmbeddedByValue()               {}

// UnsafeCallsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CallsServer will
// result in compilation errors.
type UnsafeCallsServer interface {
	mustEmbedUnimplementedCallsServer()
}

func RegisterCallsServer(s grpc.ServiceRegistrar, srv CallsServer) {
	// If the following call panics, it indicates UnimplementedCallsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Calls_ServiceDesc, srv)
}

func _Calls_StartOutgoingCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartOutgoingCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallsServer).StartOutgoingCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Calls_StartOutgoingCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallsServer).StartOutgoingCall(ctx, req.(*StartOutgoingCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calls_SubscribeCallEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeCallEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CallsServer).SubscribeCallEvents(m, &grpc.GenericServerStream[SubscribeCallEventsRequest, CallEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Calls_SubscribeCallEventsServer = grpc.ServerStreamingServer[CallEvent]

func _Calls_HangupCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HangupCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallsServer).HangupCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Calls_HangupCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallsServer).HangupCall(ctx, req.(*HangupCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Calls_ServiceDesc is the grpc.ServiceDesc for Calls service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Calls_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calls.v1.Calls",
	HandlerType: (*CallsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartOutgoingCall",
			Handler:    _Calls_StartOutgoingCall_Handler,
		},
		{
			MethodName: "HangupCall",
			Handler:    _Calls_HangupCall_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeCallEvents",
			Handler:       _Calls_SubscribeCallEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "calls.proto",
}
