// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: calls.proto

package rpc

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallProvider int32

const (
	CallProvider_CALL_PROVIDER_UNSPECIFIED CallProvider = 0
	CallProvider_CALL_PROVIDER_WHATSAPP    CallProvider = 1
	CallProvider_CALL_PROVIDER_TELEGRAM    CallProvider = 2
)

// Enum value maps for CallProvider.
var (
	CallProvider_name = map[int32]string{
		0: "CALL_PROVIDER_UNSPECIFIED",
		1: "CALL_PROVIDER_WHATSAPP",
		2: "CALL_PROVIDER_TELEGRAM",
	}
	CallProvider_value = map[string]int32{
		"CALL_PROVIDER_UNSPECIFIED": 0,
		"CALL_PROVIDER_WHATSAPP":    1,
		"CALL_PROVIDER_TELEGRAM":    2,
	}
)

func (x CallProvider) Enum() *CallProvider {
	p := new(CallProvider)
	*p = x
	return p
}

func (x CallProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_calls_proto_enumTypes[0].Descriptor()
}

func (CallProvider) Type() protoreflect.EnumType {
	return &file_calls_proto_enumTypes[0]
}

func (x CallProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallProvider.Descriptor instead.
func (CallProvider) EnumDescriptor() ([]byte, []int) {
	return file_calls_proto_rawDescGZIP(), []int{0}
}

type CallEventType int32

const (
	CallEventType_CALL_EVENT_TYPE_UNSPECIFIED CallEventType = 0
	CallEventType_CALL_STARTED                CallEventType = 1
	CallEventType_REALTIME_STARTING           CallEventType = 2
	CallEventType_REALTIME_STARTED            CallEventType = 3
	CallEventType_REALTIME_SUBSCRIBED         CallEventType = 4
	CallEventType_AUDIO_BRIDGE_STARTED        CallEventType = 5
	CallEventType_CALL_CONNECTED              CallEventType = 6
	CallEventType_INPUT_TRANSCRIPT_DELTA      CallEventType = 7
	CallEventType_INPUT_TRANSCRIPT_DONE       CallEventType = 8
	CallEventType_RESPONSE_STARTED            CallEventType = 9
	CallEventType_RESPONSE_TEXT_DELTA         CallEventType = 10
	CallEventType_RESPONSE_DONE               CallEventType = 11
	CallEventType_ERROR                       CallEventType = 12
	CallEventType_CALL_ENDED                  CallEventType = 13
)

// Enum value maps for CallEventType.
var (
	CallEventType_name = map[int32]string{
		0:  "CALL_EVENT_TYPE_UNSPECIFIED",
		1:  "CALL_STARTED",
		2:  "REALTIME_STARTING",
		3:  "REALTIME_STARTED",
		4:  "REALTIME_SUBSCRIBED",
		5:  "AUDIO_BRIDGE_STARTED",
		6:  "CALL_CONNECTED",
		7:  "INPUT_TRANSCRIPT_DELTA",
		8:  "INPUT_TRANSCRIPT_DONE",
		9:  "RESPONSE_STARTED",
		10: "RESPONSE_TEXT_DELTA",
		11: "RESPONSE_DONE",
		12: "ERROR",
		13: "CALL_ENDED",
	}
	CallEventType_value = map[string]int32{
		"CALL_EVENT_TYPE_UNSPECIFIED": 0,
		"CALL_STARTED":                1,
		"REALTIME_STARTING":           2,
		"REALTIME_STARTED":            3,
		"REALTIME_SUBSCRIBED":         4,
		"AUDIO_BRIDGE_STARTED":        5,
		"CALL_CONNECTED":              6,
		"INPUT_TRANSCRIPT_DELTA":      7,
		"INPUT_TRANSCRIPT_DONE":       8,
		"RESPONSE_STARTED":            9,
		"RESPONSE_TEXT_DELTA":         10,
		"RESPONSE_DONE":               11,
		"ERROR":                       12,
		"CALL_ENDED":                  13,
	}
)

func (x CallEventType) Enum() *CallEventType {
	p := new(CallEventType)
	*p = x
	return p
}

func (x CallEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_calls_proto_enumTypes[1].Descriptor()
}

func (CallEventType) Type() protoreflect.EnumType {
	return &file_calls_proto_enumTypes[1]
}

func (x CallEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallEventType.Descriptor instead.
func (CallEventType) EnumDescriptor() ([]byte, []int) {
	return file_calls_proto_rawDescGZIP(), []int{1}
}

type StartOutgoingCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Provider      CallProvider           `protobuf:"varint,2,opt,name=provider,proto3,enum=calls.v1.CallProvider" json:"provider,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartOutgoingCallRequest) Reset() {
	*x = StartOutgoingCallRequest{}
	mi := &file_calls_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartOutgoingCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOutgoingCallRequest) ProtoMessage() {}

func (x *StartOutgoingCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calls_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOutgoingCallRequest.ProtoReflect.Descriptor instead.
func (*StartOutgoingCallRequest) Descriptor() ([]byte, []int) {
	return file_calls_proto_rawDescGZIP(), []int{0}
}

func (x *StartOutgoingCallRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *StartOutgoingCallRequest) GetProvider() CallProvider {
	if x != nil {
		return x.Provider
	}
	return CallProvider_CALL_PROVIDER_UNSPECIFIED
}

func (x *StartOutgoingCallRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type StartOutgoingCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	AiProvider    string                 `protobuf:"bytes,3,opt,name=ai_provider,json=aiProvider,proto3" json:"ai_provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartOutgoingCallResponse) Reset() {
	*x = StartOutgoingCallResponse{}
	mi := &file_calls_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartOutgoingCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOutgoingCallResponse) ProtoMessage() {}

func (x *StartOutgoingCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calls_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOutgoingCallResponse.ProtoReflect.Descriptor instead.
func (*StartOutgoingCallResponse) Descriptor() ([]byte, []int) {
	return file_calls_proto_rawDescGZIP(), []int{1}
}

func (x *StartOutgoingCallResponse) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *StartOutgoingCallResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StartOutgoingCallResponse) GetAiProvider() string {
	if x != nil {
		return x.AiProvider
	}
	return ""
}

type SubscribeCallEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CallId        string                 `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	AfterSequence uint64                 `protobuf:"varint,3,opt,name=after_sequence,json=afterSequence,proto3" json:"after_sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeCallEventsRequest) Reset() {
	*x = SubscribeCallEventsRequest{}
	mi := &file_calls_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeCallEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeCallEventsRequest) ProtoMessage() {}

func (x *SubscribeCallEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calls_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeCallEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeCallEventsRequest) Descriptor() ([]byte, []int) {
	return file_calls_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeCallEventsRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubscribeCallEventsRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *SubscribeCallEventsRequest) GetAfterSequence() uint64 {
	if x != nil {
		return x.AfterSequence
	}
	return 0
}

type HangupCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CallId        string                 `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HangupCallRequest) Reset() {
	*x = HangupCallRequest{}
	mi := &file_calls_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HangupCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HangupCallRequest) ProtoMessage() {}

func (x *HangupCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calls_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HangupCallRequest.ProtoReflect.Descriptor instead.
func (*HangupCallRequest) Descriptor() ([]byte, []int) {
	return file_calls_proto_rawDescGZIP(), []int{3}
}

func (x *HangupCallRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *HangupCallRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *HangupCallRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type HangupCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HangupCallResponse) Reset() {
	*x = HangupCallResponse{}
	mi := &file_calls_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HangupCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HangupCallResponse) ProtoMessage() {}

func (x *HangupCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calls_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HangupCallResponse.ProtoReflect.Descriptor instead.
func (*HangupCallResponse) Descriptor() ([]byte, []int) {
	return file_calls_proto_rawDescGZIP(), []int{4}
}

func (x *HangupCallResponse) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *HangupCallResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CallEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CallId          string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Sequence        uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,3,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	Provider        CallProvider           `protobuf:"varint,4,opt,name=provider,proto3,enum=calls.v1.CallProvider" json:"provider,omitempty"`
	Type            CallEventType          `protobuf:"varint,5,opt,name=type,proto3,enum=calls.v1.CallEventType" json:"type,omitempty"`
	Delta           string                 `protobuf:"bytes,6,opt,name=delta,proto3" json:"delta,omitempty"`
	Text            string                 `protobuf:"bytes,7,opt,name=text,proto3" json:"text,omitempty"`
	ResponseId      string                 `protobuf:"bytes,8,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"`
	Reason          string                 `protobuf:"bytes,9,opt,name=reason,proto3" json:"reason,omitempty"`
	Error           string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CallEvent) Reset() {
	*x = CallEvent{}
	mi := &file_calls_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallEvent) ProtoMessage() {}

func (x *CallEvent) ProtoReflect() protoreflect.Message {
	mi := &file_calls_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallEvent.ProtoReflect.Descriptor instead.
func (*CallEvent) Descriptor() ([]byte, []int) {
	return file_calls_proto_rawDescGZIP(), []int{5}
}

func (x *CallEvent) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *CallEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *CallEvent) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *CallEvent) GetProvider() CallProvider {
	if x != nil {
		return x.Provider
	}
	return CallProvider_CALL_PROVIDER_UNSPECIFIED
}

func (x *CallEvent) GetType() CallEventType {
	if x != nil {
		return x.Type
	}
	return CallEventType_CALL_EVENT_TYPE_UNSPECIFIED
}

func (x *CallEvent) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *CallEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CallEvent) GetResponseId() string {
	if x != nil {
		return x.ResponseId
	}
	return ""
}

func (x *CallEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CallEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_calls_proto protoreflect.FileDescriptor

const file_calls_proto_rawDesc = "" +
	"\n" +
	"\vcalls.proto\x12\bcalls.v1\"\x7f\n" +
	"\x18StartOutgoingCallRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x122\n" +
	"\bprovider\x18\x02 \x01(\x0e2\x16.calls.v1.CallProviderR\bprovider\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\"m\n" +
	"\x19StartOutgoingCallResponse\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vai_provider\x18\x03 \x01(\tR\n" +
	"aiProvider\"u\n" +
	"\x1aSubscribeCallEventsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\x12%\n" +
	"\x0eafter_sequence\x18\x03 \x01(\x04R\rafterSequence\"]\n" +
	"\x11HangupCallRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"E\n" +
	"\x12HangupCallResponse\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xc6\x02\n" +
	"\tCallEvent\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12*\n" +
	"\x11timestamp_unix_ms\x18\x03 \x01(\x03R\x0ftimestampUnixMs\x122\n" +
	"\bprovider\x18\x04 \x01(\x0e2\x16.calls.v1.CallProviderR\bprovider\x12+\n" +
	"\x04type\x18\x05 \x01(\x0e2\x17.calls.v1.CallEventTypeR\x04type\x12\x14\n" +
	"\x05delta\x18\x06 \x01(\tR\x05delta\x12\x12\n" +
	"\x04text\x18\a \x01(\tR\x04text\x12\x1f\n" +
	"\vresponse_id\x18\b \x01(\tR\n" +
	"responseId\x12\x16\n" +
	"\x06reason\x18\t \x01(\tR\x06reason\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error*e\n" +
	"\fCallProvider\x12\x1d\n" +
	"\x19CALL_PROVIDER_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CALL_PROVIDER_WHATSAPP\x10\x01\x12\x1a\n" +
	"\x16CALL_PROVIDER_TELEGRAM\x10\x02*\xca\x02\n" +
	"\rCallEventType\x12\x1f\n" +
	"\x1bCALL_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fCALL_STARTED\x10\x01\x12\x15\n" +
	"\x11REALTIME_STARTING\x10\x02\x12\x14\n" +
	"\x10REALTIME_STARTED\x10\x03\x12\x17\n" +
	"\x13REALTIME_SUBSCRIBED\x10\x04\x12\x18\n" +
	"\x14AUDIO_BRIDGE_STARTED\x10\x05\x12\x12\n" +
	"\x0eCALL_CONNECTED\x10\x06\x12\x1a\n" +
	"\x16INPUT_TRANSCRIPT_DELTA\x10\a\x12\x19\n" +
	"\x15INPUT_TRANSCRIPT_DONE\x10\b\x12\x14\n" +
	"\x10RESPONSE_STARTED\x10\t\x12\x17\n" +
	"\x13RESPONSE_TEXT_DELTA\x10\n" +
	"\x12\x11\n" +
	"\rRESPONSE_DONE\x10\v\x12\t\n" +
	"\x05ERROR\x10\f\x12\x0e\n" +
	"\n" +
	"CALL_ENDED\x10\r2\x82\x02\n" +
	"\x05Calls\x12\\\n" +
	"\x11StartOutgoingCall\x12\".calls.v1.StartOutgoingCallRequest\x1a#.calls.v1.StartOutgoingCallResponse\x12R\n" +
	"\x13SubscribeCallEvents\x12$.calls.v1.SubscribeCallEventsRequest\x1a\x13.calls.v1.CallEvent0\x01\x12G\n" +
	"\n" +
	"HangupCall\x12\x1b.calls.v1.HangupCallRequest\x1a\x1c.calls.v1.HangupCallResponseB$Z\"air_whatsbot/internal/delivery/rpcb\x06proto3"

var (
	file_calls_proto_rawDescOnce sync.Once
	file_calls_proto_rawDescData []byte
)

func file_calls_proto_rawDescGZIP() []byte {
	file_calls_proto_rawDescOnce.Do(func() {
		file_calls_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calls_proto_rawDesc), len(file_calls_proto_rawDesc)))
	})
	return file_calls_proto_rawDescData
}

var file_calls_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_calls_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_calls_proto_goTypes = []any{
	(CallProvider)(0),                  // 0: calls.v1.CallProvider
	(CallEventType)(0),                 // 1: calls.v1.CallEventType
	(*StartOutgoingCallRequest)(nil),   // 2: calls.v1.StartOutgoingCallRequest
	(*StartOutgoingCallResponse)(nil),  // 3: calls.v1.StartOutgoingCallResponse
	(*SubscribeCallEventsRequest)(nil), // 4: calls.v1.SubscribeCallEventsRequest
	(*HangupCallRequest)(nil),          // 5: calls.v1.HangupCallRequest
	(*HangupCallResponse)(nil),         // 6: calls.v1.HangupCallResponse
	(*CallEvent)(nil),                  // 7: calls.v1.CallEvent
}
var file_calls_proto_depIdxs = []int32{
	0, // 0: calls.v1.StartOutgoingCallRequest.provider:type_name -> calls.v1.CallProvider
	0, // 1: calls.v1.CallEvent.provider:type_name -> calls.v1.CallProvider
	1, // 2: calls.v1.CallEvent.type:type_name -> calls.v1.CallEventType
	2, // 3: calls.v1.Calls.StartOutgoingCall:input_type -> calls.v1.StartOutgoingCallRequest
	4, // 4: calls.v1.Calls.SubscribeCallEvents:input_type -> calls.v1.SubscribeCallEventsRequest
	5, // 5: calls.v1.Calls.HangupCall:input_type -> calls.v1.HangupCallRequest
	3, // 6: calls.v1.Calls.StartOutgoingCall:output_type -> calls.v1.StartOutgoingCallResponse
	7, // 7: calls.v1.Calls.SubscribeCallEvents:output_type -> calls.v1.CallEvent
	6, // 8: calls.v1.Calls.HangupCall:output_type -> calls.v1.HangupCallResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_calls_proto_init() }
func file_calls_proto_init() {
	if File_calls_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calls_proto_rawDesc), len(file_calls_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calls_proto_goTypes,
		DependencyIndexes: file_calls_proto_depIdxs,
		EnumInfos:         file_calls_proto_enumTypes,
		MessageInfos:      file_calls_proto_msgTypes,
	}.Build()
	File_calls_proto = out.File
	file_calls_proto_goTypes = nil
	file_calls_proto_depIdxs = nil
}
