// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: calls.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallProvider int32

const (
	CallProvider_CALL_PROVIDER_UNSPECIFIED CallProvider = 0
	CallProvider_CALL_PROVIDER_WHATSAPP    CallProvider = 1
	CallProvider_CALL_PROVIDER_TELEGRAM    CallProvider = 2
)

// Enum value maps for CallProvider.
var (
	CallProvider_name = map[int32]string{
		0: "CALL_PROVIDER_UNSPECIFIED",
		1: "CALL_PROVIDER_WHATSAPP",
		2: "CALL_PROVIDER_TELEGRAM",
	}
	CallProvider_value = map[string]int32{
		"CALL_PROVIDER_UNSPECIFIED": 0,
		"CALL_PROVIDER_WHATSAPP":    1,
		"CALL_PROVIDER_TELEGRAM":    2,
	}
)

func (x CallProvider) Enum() *CallProvider {
	p := new(CallProvider)
	*p = x
	return p
}

func (x CallProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_calls_proto_enumTypes[0].Descriptor()
}

func (CallProvider) Type() protoreflect.EnumType {
	return &file_calls_proto_enumTypes[0]
}

func (x CallProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallProvider.Descriptor instead.
func (CallProvider) EnumDescriptor() ([]byte, []int) {
	return file_calls_proto_rawDescGZIP(), []int{0}
}

type StartOutgoingCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Provider      CallProvider           `protobuf:"varint,2,opt,name=provider,proto3,enum=calls.v1.CallProvider" json:"provider,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartOutgoingCallRequest) Reset() {
	*x = StartOutgoingCallRequest{}
	mi := &file_calls_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartOutgoingCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOutgoingCallRequest) ProtoMessage() {}

func (x *StartOutgoingCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calls_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOutgoingCallRequest.ProtoReflect.Descriptor instead.
func (*StartOutgoingCallRequest) Descriptor() ([]byte, []int) {
	return file_calls_proto_rawDescGZIP(), []int{0}
}

func (x *StartOutgoingCallRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *StartOutgoingCallRequest) GetProvider() CallProvider {
	if x != nil {
		return x.Provider
	}
	return CallProvider_CALL_PROVIDER_UNSPECIFIED
}

func (x *StartOutgoingCallRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type StartOutgoingCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	AiProvider    string                 `protobuf:"bytes,3,opt,name=ai_provider,json=aiProvider,proto3" json:"ai_provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartOutgoingCallResponse) Reset() {
	*x = StartOutgoingCallResponse{}
	mi := &file_calls_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartOutgoingCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOutgoingCallResponse) ProtoMessage() {}

func (x *StartOutgoingCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calls_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOutgoingCallResponse.ProtoReflect.Descriptor instead.
func (*StartOutgoingCallResponse) Descriptor() ([]byte, []int) {
	return file_calls_proto_rawDescGZIP(), []int{1}
}

func (x *StartOutgoingCallResponse) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *StartOutgoingCallResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StartOutgoingCallResponse) GetAiProvider() string {
	if x != nil {
		return x.AiProvider
	}
	return ""
}

type SubscribeCallEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CallId        string                 `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	AfterSequence uint64                 `protobuf:"varint,3,opt,name=after_sequence,json=afterSequence,proto3" json:"after_sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeCallEventsRequest) Reset() {
	*x = SubscribeCallEventsRequest{}
	mi := &file_calls_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeCallEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeCallEventsRequest) ProtoMessage() {}

func (x *SubscribeCallEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calls_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeCallEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeCallEventsRequest) Descriptor() ([]byte, []int) {
	return file_calls_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeCallEventsRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubscribeCallEventsRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *SubscribeCallEventsRequest) GetAfterSequence() uint64 {
	if x != nil {
		return x.AfterSequence
	}
	return 0
}

type HangupCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CallId        string                 `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HangupCallRequest) Reset() {
	*x = HangupCallRequest{}
	mi := &file_calls_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HangupCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HangupCallRequest) ProtoMessage() {}

func (x *HangupCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calls_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HangupCallRequest.ProtoReflect.Descriptor instead.
func (*HangupCallRequest) Descriptor() ([]byte, []int) {
	return file_calls_proto_rawDescGZIP(), []int{3}
}

func (x *HangupCallRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *HangupCallRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *HangupCallRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type HangupCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HangupCallResponse) Reset() {
	*x = HangupCallResponse{}
	mi := &file_calls_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HangupCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HangupCallResponse) ProtoMessage() {}

func (x *HangupCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calls_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HangupCallResponse.ProtoReflect.Descriptor instead.
func (*HangupCallResponse) Descriptor() ([]byte, []int) {
	return file_calls_proto_rawDescGZIP(), []int{4}
}

func (x *HangupCallResponse) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *HangupCallResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CallEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CallId          string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Sequence        uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,3,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	Provider        CallProvider           `protobuf:"varint,4,opt,name=provider,proto3,enum=calls.v1.CallProvider" json:"provider,omitempty"`
	Type            string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Delta           string                 `protobuf:"bytes,6,opt,name=delta,proto3" json:"delta,omitempty"`
	Text            string                 `protobuf:"bytes,7,opt,name=text,proto3" json:"text,omitempty"`
	ResponseId      string                 `protobuf:"bytes,8,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"`
	Reason          string                 `protobuf:"bytes,9,opt,name=reason,proto3" json:"reason,omitempty"`
	Error           string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	Role            string                 `protobuf:"bytes,11,opt,name=role,proto3" json:"role,omitempty"`
	Phase           string                 `protobuf:"bytes,12,opt,name=phase,proto3" json:"phase,omitempty"`
	Usage           *structpb.Struct       `protobuf:"bytes,13,opt,name=usage,proto3" json:"usage,omitempty"`
	Files           []*CallFile            `protobuf:"bytes,14,rep,name=files,proto3" json:"files,omitempty"`
	Payload         *structpb.Struct       `protobuf:"bytes,15,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CallEvent) Reset() {
	*x = CallEvent{}
	mi := &file_calls_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallEvent) ProtoMessage() {}

func (x *CallEvent) ProtoReflect() protoreflect.Message {
	mi := &file_calls_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallEvent.ProtoReflect.Descriptor instead.
func (*CallEvent) Descriptor() ([]byte, []int) {
	return file_calls_proto_rawDescGZIP(), []int{5}
}

func (x *CallEvent) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *CallEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *CallEvent) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *CallEvent) GetProvider() CallProvider {
	if x != nil {
		return x.Provider
	}
	return CallProvider_CALL_PROVIDER_UNSPECIFIED
}

func (x *CallEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CallEvent) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *CallEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CallEvent) GetResponseId() string {
	if x != nil {
		return x.ResponseId
	}
	return ""
}

func (x *CallEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CallEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CallEvent) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CallEvent) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *CallEvent) GetUsage() *structpb.Struct {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *CallEvent) GetFiles() []*CallFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *CallEvent) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CallFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Caption       string                 `protobuf:"bytes,4,opt,name=caption,proto3" json:"caption,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallFile) Reset() {
	*x = CallFile{}
	mi := &file_calls_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallFile) ProtoMessage() {}

func (x *CallFile) ProtoReflect() protoreflect.Message {
	mi := &file_calls_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallFile.ProtoReflect.Descriptor instead.
func (*CallFile) Descriptor() ([]byte, []int) {
	return file_calls_proto_rawDescGZIP(), []int{6}
}

func (x *CallFile) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CallFile) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CallFile) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *CallFile) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

var File_calls_proto protoreflect.FileDescriptor

const file_calls_proto_rawDesc = "" +
	"\n" +
	"\vcalls.proto\x12\bcalls.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x7f\n" +
	"\x18StartOutgoingCallRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x122\n" +
	"\bprovider\x18\x02 \x01(\x0e2\x16.calls.v1.CallProviderR\bprovider\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\"m\n" +
	"\x19StartOutgoingCallResponse\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vai_provider\x18\x03 \x01(\tR\n" +
	"aiProvider\"u\n" +
	"\x1aSubscribeCallEventsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\x12%\n" +
	"\x0eafter_sequence\x18\x03 \x01(\x04R\rafterSequence\"]\n" +
	"\x11HangupCallRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"E\n" +
	"\x12HangupCallResponse\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xe3\x03\n" +
	"\tCallEvent\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12*\n" +
	"\x11timestamp_unix_ms\x18\x03 \x01(\x03R\x0ftimestampUnixMs\x122\n" +
	"\bprovider\x18\x04 \x01(\x0e2\x16.calls.v1.CallProviderR\bprovider\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x14\n" +
	"\x05delta\x18\x06 \x01(\tR\x05delta\x12\x12\n" +
	"\x04text\x18\a \x01(\tR\x04text\x12\x1f\n" +
	"\vresponse_id\x18\b \x01(\tR\n" +
	"responseId\x12\x16\n" +
	"\x06reason\x18\t \x01(\tR\x06reason\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\x12\x12\n" +
	"\x04role\x18\v \x01(\tR\x04role\x12\x14\n" +
	"\x05phase\x18\f \x01(\tR\x05phase\x12-\n" +
	"\x05usage\x18\r \x01(\v2\x17.google.protobuf.StructR\x05usage\x12(\n" +
	"\x05files\x18\x0e \x03(\v2\x12.calls.v1.CallFileR\x05files\x121\n" +
	"\apayload\x18\x0f \x01(\v2\x17.google.protobuf.StructR\apayload\"g\n" +
	"\bCallFile\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x18\n" +
	"\acaption\x18\x04 \x01(\tR\acaption*e\n" +
	"\fCallProvider\x12\x1d\n" +
	"\x19CALL_PROVIDER_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CALL_PROVIDER_WHATSAPP\x10\x01\x12\x1a\n" +
	"\x16CALL_PROVIDER_TELEGRAM\x10\x022\x82\x02\n" +
	"\x05Calls\x12\\\n" +
	"\x11StartOutgoingCall\x12\".calls.v1.StartOutgoingCallRequest\x1a#.calls.v1.StartOutgoingCallResponse\x12R\n" +
	"\x13SubscribeCallEvents\x12$.calls.v1.SubscribeCallEventsRequest\x1a\x13.calls.v1.CallEvent0\x01\x12G\n" +
	"\n" +
	"HangupCall\x12\x1b.calls.v1.HangupCallRequest\x1a\x1c.calls.v1.HangupCallResponseB$Z\"air_whatsbot/internal/delivery/rpcb\x06proto3"

var (
	file_calls_proto_rawDescOnce sync.Once
	file_calls_proto_rawDescData []byte
)

func file_calls_proto_rawDescGZIP() []byte {
	file_calls_proto_rawDescOnce.Do(func() {
		file_calls_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calls_proto_rawDesc), len(file_calls_proto_rawDesc)))
	})
	return file_calls_proto_rawDescData
}

var file_calls_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_calls_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_calls_proto_goTypes = []any{
	(CallProvider)(0),                  // 0: calls.v1.CallProvider
	(*StartOutgoingCallRequest)(nil),   // 1: calls.v1.StartOutgoingCallRequest
	(*StartOutgoingCallResponse)(nil),  // 2: calls.v1.StartOutgoingCallResponse
	(*SubscribeCallEventsRequest)(nil), // 3: calls.v1.SubscribeCallEventsRequest
	(*HangupCallRequest)(nil),          // 4: calls.v1.HangupCallRequest
	(*HangupCallResponse)(nil),         // 5: calls.v1.HangupCallResponse
	(*CallEvent)(nil),                  // 6: calls.v1.CallEvent
	(*CallFile)(nil),                   // 7: calls.v1.CallFile
	(*structpb.Struct)(nil),            // 8: google.protobuf.Struct
}
var file_calls_proto_depIdxs = []int32{
	0, // 0: calls.v1.StartOutgoingCallRequest.provider:type_name -> calls.v1.CallProvider
	0, // 1: calls.v1.CallEvent.provider:type_name -> calls.v1.CallProvider
	8, // 2: calls.v1.CallEvent.usage:type_name -> google.protobuf.Struct
	7, // 3: calls.v1.CallEvent.files:type_name -> calls.v1.CallFile
	8, // 4: calls.v1.CallEvent.payload:type_name -> google.protobuf.Struct
	1, // 5: calls.v1.Calls.StartOutgoingCall:input_type -> calls.v1.StartOutgoingCallRequest
	3, // 6: calls.v1.Calls.SubscribeCallEvents:input_type -> calls.v1.SubscribeCallEventsRequest
	4, // 7: calls.v1.Calls.HangupCall:input_type -> calls.v1.HangupCallRequest
	2, // 8: calls.v1.Calls.StartOutgoingCall:output_type -> calls.v1.StartOutgoingCallResponse
	6, // 9: calls.v1.Calls.SubscribeCallEvents:output_type -> calls.v1.CallEvent
	5, // 10: calls.v1.Calls.HangupCall:output_type -> calls.v1.HangupCallResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_calls_proto_init() }
func file_calls_proto_init() {
	if File_calls_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calls_proto_rawDesc), len(file_calls_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calls_proto_goTypes,
		DependencyIndexes: file_calls_proto_depIdxs,
		EnumInfos:         file_calls_proto_enumTypes,
		MessageInfos:      file_calls_proto_msgTypes,
	}.Build()
	File_calls_proto = out.File
	file_calls_proto_goTypes = nil
	file_calls_proto_depIdxs = nil
}
